version: '3.8'

services:
  enigma-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: fr4iser/enigma:frontend
    container_name: enigma-frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  enigma-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fr4iser/enigma:backend
    container_name: enigma-backend
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  frontend_logs:
    driver: local
  backend_logs:
    driver: local
