version: '3.8'

services:
  codebreaker-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: fr4iser/enigma:frontend
    container_name: codebreaker-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://codebreaker-backend-service:8000
    volumes:
      - ./frontend/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  codebreaker-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: fr4iser/enigma:backend
    container_name: codebreaker-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ALLOWED_ORIGINS=http://codebreaker-frontend:3000,http://localhost:3000
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  frontend_logs:
    driver: local
  backend_logs:
    driver: local
